env: flex
runtime: nodejs
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  min_idle_instances: 0
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5